In [22]:
import sqlite3

# Connect to database (or create it)
conn = sqlite3.connect('USERS1.db')
curs = conn.cursor()

# Create table if it doesn't exist
curs.execute("""
CREATE TABLE IF NOT EXISTS USERS1 (
    ID INTEGER PRIMARY KEY AUTOINCREMENT , 
    NAME TEXT NOT NULL,
    AGE INTEGER NOT NULL
)
""")

# Insert records (ID will auto-increment if not provided)
curs.execute("INSERT INTO USERS1 (ID, NAME, AGE) VALUES (?, ?, ?)", (1, "Shabna", 25))
curs.execute("INSERT INTO USERS1 (ID, NAME, AGE) VALUES (?, ?, ?)", (2, "Sheenu", 28))

# Commit changes
conn.commit()

# Fetch and display all records
curs.execute("SELECT * FROM USERS1")
rows = curs.fetchall()
for row in rows:
    print(row)

# Close connection
conn.close()


(1, 'Shabna', 25)
(2, 'Sheenu', 28)


In [1]:
import numpy as np
new=np.array([1,2,3,4,5])
print(new)

[1 2 3 4 5]


In [3]:
print(new.shape)

(5,)


In [5]:
d2=np.array([[1,2],[3,4]])
print(d2)
print(d2.shape)

[[1 2]
 [3 4]]
(2, 2)


In [8]:
d3=np.array([[[1,2],[3,4]],[[3,7],[5,6]]])
print(d3)
print(d3.shape)

[[[1 2]
  [3 4]]

 [[3 7]
  [5 6]]]
(2, 2, 2)


In [9]:
var=np.random.randint(1,10,size=(2,2,3,4))
print(var)


[[[[4 3 9 4]
   [9 6 6 7]
   [1 7 6 6]]

  [[3 1 1 9]
   [8 5 7 3]
   [9 7 5 9]]]


 [[[8 2 2 3]
   [6 6 2 3]
   [2 2 1 9]]

  [[5 4 5 7]
   [2 7 9 2]
   [4 4 1 4]]]]


In [10]:
print(var.shape)

(2, 2, 3, 4)


In [13]:
from numpy import random
x=random.randint(1,100,size=(3,5))
print(x)

[[76 79 88 36 25]
 [10 50 50 92 13]
 [95  5 43 29 43]]


In [14]:
py_li=[1,2,3,4]
np_array=np.array([1,2,3,4])
print(py_li*2)
print(np_array*2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [ ]:
#Array Inspection

In [15]:
#1. shape
y=np.array([[1,2],[3,4]])
print(y.shape)

(2, 2)


In [18]:
#2. ndim
z=np.array([1,2,3,4])
w=np.array([[[1,2],[3,4],[5,6]]])
print(y.ndim)
print(z.ndim)
print(w.ndim)

2
1
3


In [20]:
#3. size
print(w.size)
print(z.size)
print(y.size)

6
4
4


In [21]:
#4. dtype
print(w.dtype)

int64


In [22]:
str=np.array(['a','b','c','d'])
print(str.dtype)

<U1


In [23]:
fl=np.array([1.2,3.0,9.8])
print(fl.dtype)

float64


In [26]:
#5. astype
fl=np.array([1.2,3.0,9.8])
print(fl)
flnew=fl.astype('int64')
print(flnew)
print(flnew.dtype)

[1.2 3.  9.8]
[1 3 9]
int64


In [33]:
import sys
np_list=[1,2,3,4,5,6]
np_array=np.array([1,2,3,4,5,6])
print("Size of each elements in a list in bytes",sys.getsizeof(np_list))
print("Size of whole elements in a list in bytes",sys.getsizeof(np_list)*len(np_list))
print("Size of each elements in an array in bytes",np_array.itemsize)
print("Size of whole elements in an array in bytes",np_array.itemsize*np_array.size)

Size of each elements in a list in bytes 104
Size of whole elements in a list in bytes 624
Size of each elements in an array in bytes 8
Size of whole elements in an array in bytes 48


In [11]:
import numpy as np
import time

# size of arrays and lists
size = 100000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

# capturing time before the multiplication of Python lists
initialTime = time.time()

# multiplying  elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying  elements of both the Numpy arrays and stored in another Numpy array
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists to perform multiplication: 0.009866476058959961 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0006954669952392578 seconds


In [39]:
#Different ways of creating an ndarray
#1. zeros

ar1=np.zeros((3,3))
print(ar1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
ar1=np.zeros((3,3),dtype=int)
print(ar1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
#2. ones

ar2=np.ones((2,2))
print(ar2)

[[1. 1.]
 [1. 1.]]


In [42]:
ar2=np.ones((2,2),dtype=int)
print(ar2)

[[1 1]
 [1 1]]


In [43]:
#3. arange

ar3=np.arange(3)
print(ar3)

[0 1 2]


In [44]:
ar4=np.arange(10)
print(ar4)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
#4. full

ar5=np.full((2,2),10)
print(ar5)

[[10 10]
 [10 10]]


In [46]:
ar6=np.full((3,3),2)
print(ar6)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [50]:
#5. identity

ar7=np.identity((4),dtype=int)
print(ar7)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [51]:
ar7=np.identity((4))
print(ar7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:

lis=[1,2,3]
ar1=np.asarray(lis)
print(ar1)
ar1

[1 2 3]


array([1, 2, 3])

In [4]:
tup=(1,2,3)
ar2=np.asarray(tup)
ar2

array([1, 2, 3])

In [9]:
#Array Slicing & Indexing
#1D Array

a=np.arange(10)
print(a[2:])
print(a[1:9])
print(a[::3])


[2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]
[0 3 6 9]


In [14]:
b=np.random.random(10)
print(b[:8])


[0.48590042 0.38069289 0.03376708 0.62681911 0.76775111 0.10191366
 0.91966813 0.79765939]


In [16]:
#2D array slicing

c=np.array([[1,2,3],[4,5,6]])
print(c[0:2])

[[1 2 3]
 [4 5 6]]


In [19]:
print(c[1:])

[[4 5 6]]


In [21]:
print(c[0:2,-2:])

[[2 3]
 [5 6]]


In [23]:
print(c[1,2])

6


In [30]:
#3D array Slicing
var1=np.random.randint(9,size=(3,3,2))
print(var1)


[[[3 7]
  [5 0]
  [1 3]]

 [[5 2]
  [5 7]
  [7 3]]

 [[6 7]
  [3 1]
  [4 1]]]


In [31]:
print(var1[0:2])

[[[3 7]
  [5 0]
  [1 3]]

 [[5 2]
  [5 7]
  [7 3]]]


In [43]:
print(var1[0:2,1:])

[[[5 0]
  [1 3]]

 [[5 7]
  [7 3]]]


In [47]:
print(var1[0:2,1:,0])

[[5 1]
 [5 7]]


In [41]:
print(var1.shape)

(3, 3, 2)


In [42]:
var2=np.array([[[1,2],[3,5]],
               [[6,7],[8,9]]])
print(var2.shape)   #2 layer, 2 Row, 2 Column

(2, 2, 2)


In [64]:
#array bManipulation
# 1.Transpose

var3=np.random.randint(10,size=(3,2))
print(var3.shape)
print(var3)
var5=np.transpose(var3)
print(var5.shape)
print(var5)

(3, 2)
[[9 4]
 [5 2]
 [9 8]]
(2, 3)
[[9 5 9]
 [4 2 8]]


In [66]:
# 2.Reshape

var4=(1,2,3)
var6=np.reshape(var3,var4)
print(var6)

[[[9 4 5]
  [2 9 8]]]


In [67]:
# 3.Resize
var8=(2,3,2)
var7=np.resize(var3,var8)
print(var7)

[[[9 4]
  [5 2]
  [9 8]]

 [[9 4]
  [5 2]
  [9 8]]]


In [71]:
#4. flatten

print(var3.flatten())

[9 4 5 2 9 8]
